Repository xruben136x/SZZ_unisannio, pull requests merged in 2023-11, with the labels that each got.

#5 Managment single line comments
  Szz_baseline.ipynb
Labels: ChatGPT_Integration

#10 Tool generalized
  notebooks/Szz_baseline.ipynb
Labels: enhancement

#12 Modification for the collecting commits that introduced bugs
  src/algorithm/main.py
Labels: ChatGPT_Integration, Minor Adjustment

#16 Changed implementation of the issue tracker version.
  src/algorithm/main_issue.py
Labels: enhancement, issue-tracker

#18 Integrated all functionality in a single version.
  notebooks/SZZ_baseline_issue.ipynb
  notebooks/Szz_baseline.ipynb
  src/algorithm/main.py
  src/algorithm/main_issue.py
Labels: enhancement, ChatGPT_Integration

#20 Refactoring, code restructuring.
  src/algorithm/main_issue.py
Labels: ChatGPT_Integration, Refactoring

#22 Added the feature "search most recent commit".
  src/algorithm/main.py
  src/algorithm/main_issue.py
Labels: enhancement, ChatGPT_Integration

#27 Added retrieve from 'regex_file.txt'
  README.md
  regex_config.txt
  src/algorithm/main.py
Labels: enhancement, ChatGPT_Integration

#29 Refactoring code
  src/algorithm/main.py
Labels: Refactoring

#34 Test automation
  .github/workflows/build.yaml
Labels: ChatGPT_Integration, CI/CD

#35 Testing branch merge
  .github/workflows/build.yaml
  src/algorithm/main.py
  tests/unit_test/UnitTest.py
  tests/unit_test/__pycache__/UnitTest.cpython-311.pyc
Labels: Testing

#37 Report automation
  .github/workflows/build.yaml
  requirements.txt
  src/main.py
  tests/test_unit.py
Labels: ChatGPT_Integration, CI/CD
